# This is a basic workflow to help you get started with Actions

name: CI

on:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:
  build:

    runs-on: ubuntu-latest
ob
    steps:
      - uses: actions/checkout@v3

      - name: Run make command
        run: make all
